### PR TITLE
1 create a first structure of the package

### PR DESCRIPTION
**Pull request by joergfunger**
I created a first structure for the repository and added some information in the readme. This should now generate virtual data (see documention) that can be used e.g. by 7.5. I have also set up the github actions that run whenever some pushes, which will allow us to do continuous integration checks. Please have a look at the readme.md for a short documentation, if there is more necessary, please let me know.
@gdmiron Should we also invite the 7.5 to the repo (and potentially make them reviewer) such that they are aware of that?

### CODE REVIEW

**Comment by joergfunger** [comment]
@gdmiron  did you have a look at the merge request? @linnosma did you check, if this is working with you?

**Comment by gdmiron** [comment]
@joergfunger, I try to have a look this coming week. Happy new year!

**Comment by gdmiron** [comment]
Based on the example, as a staring point, I made an extended json sensor metadata and its schema. I can add this in a separate pull request + the changes to the code to adhere to this structure. 

Metadata for two sensors:
```json
[{
    "sensor_id": "sensor-001",
    "package_id": "package-001",
    "position": {
        "location": [0, 1, 0]
    },
    "measuring_quantity" :       {
        "type": "temperature",
        "unit": "K"
      },
    "independent_variable":       {
        "type": "time",
        "unit": "s"
      }
  },
  {
    "sensor_id": "sensor-002",
    "package_id": "package-001",
    "position": {
        "location": [0, 2, 0],
        "orientation": [1, 0, 0]
    },
    "measuring_quantity" :       {
        "type": "displacement",
        "unit": "m"
      },
    "independent_variable":       {
        "type": "time",
        "unit": "s"
      }
  }]
``` 
and its schema that describes its structure:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Waste Package Monitoring Sensor Metadata",
    "description": "Metadata for a waste package monitoring sensor, including its unique identifier, position, and measurement capabilities.",
    "type": "object",
    "required": [
        "sensor_id",
        "position",
        "measuring_quantity"
    ],
    "properties": {
        "sensor_id": {
            "description": "A unique identifier for the sensor.",
            "type": "string"
        },
        "package_id": {
            "description": "A unique identifier for the Waste Package where the sensor is placed.",
            "type": "string"
        },
        "position": {
            "description": "The position of the sensor defined by location and optional orientation.",
            "type": "object",
            "required": [
                "location"
            ],
            "properties": {
                "location": {
                    "description": "The XYZ coordinates of the sensor.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "orientation": {
                    "description": "The XYZ coordinates of the orientation.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "measuring_quantity": {
            "description": "The type of measurement that the sensor is capable of taking.",
            "type": "object",
            "required": [
                "type",
                "unit"
            ],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "temperature", "displacement", "radioactivity", "humidity"
                    ]
                },
                "unit": {
                    "description": "SI unit.",
                    "type": "string"
                }
            }
        },
        "independent_variable": {
            "description": "The chosen variable to make the measurements as a function of.",
            "type": "object",
            "required": [
                "type",
                "unit"
            ],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "time"
                    ]
                },
                "unit": {
                    "description": "SI unit.",
                    "type": "string"
                }
            }
        }
    }
}
```

**Review by gdmiron — APPROVED** [review]

**Comment by joergfunger** [comment]
> Based on the example, as a staring point, I made an extended json sensor metadata and its schema. I can add this in a separate pull request + the changes to the code to adhere to this structure.
> 
> Metadata for two sensors:
> 
> ```json
> [{
>     "sensor_id": "sensor-001",
>     "package_id": "package-001",
>     "position": {
>         "location": [0, 1, 0]
>     },
>     "measuring_quantity" :       {
>         "type": "temperature",
>         "unit": "K"
>       },
>     "independent_variable":       {
>         "type": "time",
>         "unit": "s"
>       }
>   },
>   {
>     "sensor_id": "sensor-002",
>     "package_id": "package-001",
>     "position": {
>         "location": [0, 2, 0],
>         "orientation": [1, 0, 0]
>     },
>     "measuring_quantity" :       {
>         "type": "displacement",
>         "unit": "m"
>       },
>     "independent_variable":       {
>         "type": "time",
>         "unit": "s"
>       }
>   }]
> ```
> 
> and its schema that describes its structure:
> 
> ```json
> {
>     "$schema": "http://json-schema.org/draft-07/schema#",
>     "title": "Waste Package Monitoring Sensor Metadata",
>     "description": "Metadata for a waste package monitoring sensor, including its unique identifier, position, and measurement capabilities.",
>     "type": "object",
>     "required": [
>         "sensor_id",
>         "position",
>         "measuring_quantity"
>     ],
>     "properties": {
>         "sensor_id": {
>             "description": "A unique identifier for the sensor.",
>             "type": "string"
>         },
>         "package_id": {
>             "description": "A unique identifier for the Waste Package where the sensor is placed.",
>             "type": "string"
>         },
>         "position": {
>             "description": "The position of the sensor defined by location and optional orientation.",
>             "type": "object",
>             "required": [
>                 "location"
>             ],
>             "properties": {
>                 "location": {
>                     "description": "The XYZ coordinates of the sensor.",
>                     "type": "array",
>                     "items": {
> ```

could you make an issue or merge request, this way we could discuss that in more detail without polluting this merge request.

**Comment by joergfunger** [comment]
> I had a look over the code and run the data generation example. I think this is a good start to build upon.
> 
> Should we not call the function found in digitaltwin also for the virtual data generation? Sort of the same code is found in both places.
> 
> Next we should see how to connect to azure to write and read data @linnosma. Or just use the code inside a virtual machine in azure to connect to a database.

In the future, those might be different tasks, such that we could clearly introduce different methods for the generation of data (e.g. a quadratic function) and for the identification use only a linear function.

**Pull request merged**
